goog.addDependency('../../../../bower_components/jquery/dist/jquery.js', ['libs.jquery'], [], false);
goog.addDependency('../../../../bower_components/bootstrap/dist/js/bootstrap.min.js', ['libs.bootstrap'], ['libs.jquery'], false);
goog.addDependency('../../../../bower_components/bootstrap-material-design/dist/js/ripples.min.js', ['libs.material.ripples'], ['libs.bootstrap'], false);
goog.addDependency('../../../../bower_components/bootstrap-material-design/dist/js/material.min.js', ['libs.material'], ['libs.material.ripples'], false);

goog.addDependency('../../../../bower_components/angular/angular.js', ['libs.angular'], ['libs.jquery'], false);
goog.addDependency('../../../../bower_components/angular-ui-router/release/angular-ui-router.js', ['libs.angular.ui.router'], ['libs.angular'], false);
goog.addDependency('../../../../bower_components/angular-ui-router.stateHelper/statehelper.js', ['libs.angular.ui.router.statehelper'], ['libs.angular.ui.router'], false);

// This file was autogenerated by bower_components/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../js/app.js', ['app.module'], ['app.videojs.module', 'app.videojs.state', 'libs.angular', 'libs.angular.ui.router.statehelper', 'libs.material'], false);
goog.addDependency('../../../../js/states/app.videojs.RSSModel.js', ['app.videojs.RSSModel'], [], false);
goog.addDependency('../../../../js/states/app.videojs.ViewStateController.js', ['app.videojs.ViewStateController'], [], false);
goog.addDependency('../../../../js/states/app.videojs.player.Directive.js', ['app.videojs.player.Directive'], [], false);
goog.addDependency('../../../../js/states/videojs.module.js', ['app.videojs.module', 'app.videojs.state'], ['app.videojs.RSSModel', 'app.videojs.ViewStateController', 'app.videojs.player.Directive', 'libs.angular'], false);
