// This file was autogenerated by bower_components/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../js/app.js', ['app.module'], ['app.videojs.module', 'app.videojs.state', 'libs.angular', 'libs.angular.ui.router.statehelper', 'libs.material'], false);
goog.addDependency('../../../../js/states/app.videojs.RSSModel.js', ['app.videojs.RSSModel'], [], false);
goog.addDependency('../../../../js/states/app.videojs.ViewStateController.js', ['app.videojs.ViewStateController'], [], false);
goog.addDependency('../../../../js/states/app.videojs.player.Directive.js', ['app.videojs.player.Directive'], [], false);
goog.addDependency('../../../../js/states/videojs.module.js', ['app.videojs.module', 'app.videojs.state'], ['app.videojs.RSSModel', 'app.videojs.ViewStateController', 'app.videojs.player.Directive', 'libs.angular'], false);
